### ISSUE TITLE
output_dir -  invalid syntax error message

### ISSUE THREAD

**Issue by almullaonline** [YashTotale/goodreads-user-scraper#6]
**Describe the bug**
 invalid syntax message will appear when running the --output_dir 

![02](https://user-images.githubusercontent.com/125236900/225305477-d30b5f75-3de3-48b7-9318-658a2fb27b4f.png)

**Using:**
Visual Studio Code

**Comment by YashTotale** [comment]
Your command should be `goodreads-user-scraper --user-id 5823658 --output-dir goodreads-data`
